### ISSUE TITLE
app_ethernet_demo may contain usefull code

### ISSUE THREAD

**Issue by interactive-matter** [xcore/sc_ethernet#19]
Hi,

it is not really an issue that there is some useful code in app_ethernet_demo. But perhaps it should be availlable as a library of nice small helper functions. I think those functions are perhaps usefull for other applications (at least I think so for my app_led_tile):

is_ethertype (?)
is_mac_addr
is_broadcast

build_arp_response
is_valid_arp_packet

build_icmp_response
is_valid_icmp_packet
And perhaps the ARP/ICMP handling in the demo funxtion. 

I will try to copy tht over to the app_led_tile and test if it works well enough for me. Then I will see it is worth a pull request for the sc_ethernet.

So you have to do nothing until I got more results ;)

Marcus

**Comment by DavidNorman** [comment]
hooray - that’s the kind of email I like

-----Original Message-----
From: Interactive Matter [mailto:reply@reply.github.com] 
Sent: 13 December 2011 10:07
To: David Norman
Subject: [sc_ethernet] app_ethernet_demo may contain usefull code (#19)

Hi,

it is not really an issue that there is some useful code in app_ethernet_demo. But perhaps it should be availlable as a library of nice small helper functions. I think those functions are perhaps usefull for other applications (at least I think so for my app_led_tile):

is_ethertype (?)
is_mac_addr
is_broadcast

build_arp_response
is_valid_arp_packet

build_icmp_response
is_valid_icmp_packet
And perhaps the ARP/ICMP handling in the demo funxtion. 

I will try to copy tht over to the app_led_tile and test if it works well enough for me. Then I will see it is worth a pull request for the sc_ethernet.

So you have to do nothing until I got more results ;)

Marcus

---

Reply to this email directly or view it on GitHub:
https://github.com/xcore/sc_ethernet/issues/19
