### ISSUE TITLE
Only "app_ethernet_tests" builds of the app

### ISSUE THREAD

**Issue by lilltroll77** [xcore/sc_ethernet#2]
I'm a little new to the "dual layer makefiles", but when building the project, only the app_ethernet_tests builds, leaving the other applications unbuilt, is that the intention ?

Reading the "master" makefile, I understands it as:
app_ethernet_demo, app_ethernet_loopback and app_ethernet_tests
should build by default, but it doesn't !?

**Comment by ghost** [comment]
This is my fault. I accidentally checked in the .cproject file with the default make target being "app_ethernet_tests.all" instead of "all" (see Building Apps in https://github.com/xcore/Community/wiki/Repository-usage).

**Comment by DavidNorman** [comment]
Hi,

I guess Dave said it all.

typically i start in the root directory and just do 'xmake all'.  if i want to build only a particular app/test I go into the app_xxx or test_xxx directory and do 'xmake all' in there.
