### ISSUE TITLE
mii.xc build issue

### ISSUE THREAD

**Issue by andrew-elder** [xcore/sc_ethernet#8]
Dave,

Yes,  I know, I should be figuring out how to create a fork to report this. Anyway, around line 188 of mii.xc the source code is

```
    if (!dptr_hp) dptr_hp = dptr_lp;
```

This line gives me a compile error. I think it should instead be
# ifdef ETHERNET_RX_HP_QUEUE

```
    if (!dptr_hp) dptr_hp = dptr_lp;
```
# endif

Thanks,
Andrew

**Comment by DavidNorman** [comment]
You're right.   Doh!   - I've been working on getting AVB working perfectly, and I guess I have been a bit slack in checking that the ethernet module compiles on its own.  There's less than 2 weeks to the AVnu plugfest where we're testing our AVB implementation against other companies.

I'll make the change immediately. thanks for the info
